### ISSUE TITLE
Provide way to skip compileOnly dependencies

### ISSUE THREAD

**Issue by jeremylong** [dependency-check/dependency-check-gradle#142]
Create a mechanism to skip [compileOnly](https://blog.gradle.org/introducing-compile-only-dependencies) dependencies.

(this ticket was moved from the core dependency-check issue tracker here: https://github.com/jeremylong/DependencyCheck/issues/2149)

**Comment by jeremylong** [comment]
Pretty sure this can be accomplished using existing features:

```groovy
dependencyCheck {
   skipConfigurations = ['compileOnly', 'compileClasspath']
}
```

**Comment by wojteo** [comment]
It works properly for _compileOnly_ and _compileClasspath_, but is there a limit which configurations can be skipped? 
I have dependencies with _providedCompile_ for which following configuration doesn't work:
```
dependencyCheck {
   skipConfigurations = ['compileOnly', 'compileClasspath', 'providedCompile', 'testImplementation']
}
```
After changing dependencies from _providedCompile_ to both _compileClasspath_ and _testImplementation_, vulnerabilities are not shown in report.

**Comment by Krannthi** [comment]
I am using org.owasp:dependency-check-gradle:5.3.2 and couldn't get this working
dependencyCheck {
	skipConfigurations  = ['compileOnly']
        failBuildOnCVSS=1
}
