### ISSUE TITLE
Do not identify files multiple times

### ISSUE THREAD

**Issue by Vampire** [dependency-check/dependency-check-gradle#168]
We have a rather big multi-project build.
There are several sub-projects with the actual business logic and a few aggregator projects that produce the final artifacts (an ear, two wars, and a zip).
If I just apply the plugin and use the aggregate task, it runs for half an hour.
If I restrict the projects to the aggregator projects, the whole build needs about 2 minutes and finds almost the same issues. The differences are only in `compileOnly` dependencies, so not really relevant.

It is not the actual analyzers that consume the time, but it is the collecting of the artifacts to analyze in the Gradle plugin that needs most of the time.
I'd like to suggest to there have some facility that for example remembers by file path, or checksum or whatever, that the file is already analyzed and identified.
I'd prefer to just analyze all projects to not accidentally forget something that for example gets added later, but not for 1500% time penalty.

**Comment by jeremylong** [comment]
I'm betting a lot of this time was during checksum calculation. Enahancements have been made to 5.3.1 (which should be released soon) that made a huge improvement in scan time for larger projects that might have duplicates.

**Comment by jeremylong** [comment]
I believe this is fixed.
