### ISSUE TITLE
Ques: How to config dependencyCheckAnalyze to exclude scanning {user_home}\.gradle\caches?

### ISSUE THREAD

**Issue by Deepak-D** [dependency-check/dependency-check-gradle#184]
Ques: How to config `dependencyCheckAnalyze` to exclude scanning `{user_home}\.gradle\caches`?

I couldn't manage to config dependencyCheckAnalyze to exclude scanning gradle caches while producing report. As a result, the report includes vulnerability ids of old version of the dependencies.

**Comment by jeremylong** [comment]
Can you share your dependency-check configuration?

**Comment by Deepak-D** [comment]
Hello @jeremylong, Thanks for getting back to me. I have posted below the configuration which I have used in my gradle project build script.
```
apply plugin: 'org.owasp.dependencycheck'

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'org.owasp:dependency-check-gradle:5.3.0'
    }
}
repositories {
    jcenter()
}

version '1.1.3'

//Project dependencies
dependencies {
	compileOnly fileTree(dir: '../libs', include: '*.jar')
}
wrapper{
    gradleVersion = '5.6.4'
}
```

**Comment by jeremylong** [comment]
Any configuration of dependency check added to this? How did you run dependency check?

**Comment by Deepak-D** [comment]
Hello @jeremylong, I referred [here](https://jeremylong.github.io/DependencyCheck/dependency-check-gradle/index.html) for configuration. It says to invoke plugin, and add dependency. I did and when I do grade refresh, I see dependency check tasks listed in gradle tasks. From there, I'm running task 'dependencyCheckAnalyze' to produce report.

**Comment by jeremylong** [comment]
I'm not able to reproduce this issue. If you use the project report plugin:

```groovy
apply plugin: 'project-report'
```

Then generate the report:
```
./gradlew htmlDependencyReport
```

Are the old versions listed in any of the configuration scopes?
