### ISSUE TITLE
Warning from dotnet analyzer even when assemblyEnabled = false

### ISSUE THREAD

**Issue by fransflippo** [dependency-check/dependency-check-gradle#190]
In my `build.gradle` I'm configuring the dependency-check-gradle plugin to disable the dotnet assembly analyzer:

```
    dependencyCheck {
        suppressionFile = rootProject.file('suppression.xml')
        analyzers {
            assemblyEnabled = false
        }
        formats = [ "HTML", "XML" ]
    }
```

Yet I still get this warning:
```
Checking for updates and analyzing dependencies for vulnerabilities
----------------------------------------------------
.NET Assembly Analyzer could not be initialized and at least one 'exe' or 'dll' was scanned. The 'dotnet' executable could not be found on the path; either disable the Assembly Analyzer or add the path to dotnet core in the configuration
----------------------------------------------------
```

**Comment by jeremylong** [comment]
Sorry for the delayed response - what version of ODC are you using?

**Comment by fransflippo** [comment]
Hi! I’m away but will yet you know next week. Thanks!

**Comment by fransguelinckx** [comment]
Im getting the same warning, despite having configured the assembly analyzer to be disabled.
Gradle version: 6.8.3
Plugin version: 6.1.3

**Comment by wbervoets** [comment]
I'm also getting this warning with 6.2.0 after having configured the assembly analyzer to be disabled:

`dependencyCheck {
    analyzers.assemblyEnabled = false
...
}`

**Comment by jeremylong** [comment]
A fix will be included in the next release.
