### ISSUE TITLE
Cannot configure cve section with >5.2.2 version of plugin

### ISSUE THREAD

**Issue by markjfisher** [dependency-check/dependency-check-gradle#198]
Hi,

I'm trying to configure the cve block in our gradle build script, but anything beyond 5.2.2 causes an error.

Here's a sample build script (build.gradle.kts):

    plugins {
      id("org.owasp.dependencycheck") version "5.2.3"
    }

    repositories {
      mavenCentral()
    }
    
    dependencyCheck {
      cve {
        urlModified = "https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-modified.json.gz"
        urlBase = "https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2020.json.gz"
      }
    }

Changing down to 5.2.2 works fine (just running "gradle").

The error is:

    Line 11:   cve {
                   ^ Type mismatch: inferred type is () -> Unit but Closure<(raw) Any!>! was expected

**Comment by markjfisher** [comment]
In intellij, the 5.2.2 version of "cve" links through to this code in "org.gradle.kotlin.dsl.Accessors":

    /**
     * Configures the [cve][org.owasp.dependencycheck.gradle.extension.CveExtension] extension.
     */
    fun org.owasp.dependencycheck.gradle.extension.DependencyCheckExtension.`cve`(configure: 
    org.owasp.dependencycheck.gradle.extension.CveExtension.() -> Unit): Unit =
        (this as org.gradle.api.plugins.ExtensionAware).extensions.configure("cve", configure)

but after 5.2.2 it links through to

    public Object cve(Closure configClosure) {
        CallSite[] var2 = $getCallSiteArray();
        return var2[10].call(this.project, this.cve, configClosure);
    }

Is there an easy fix for this? Am I mis-configuring the dependencyCheck section?

**Comment by jeremylong** [comment]
I just ran a test:

```groovy
plugins {
    id 'org.owasp.dependencycheck' version '6.0.1'
    id 'org.padler.gradle.minify' version '1.5.1'
    id 'java'
}

sourceCompatibility = JavaVersion.VERSION_1_8
targetCompatibility = sourceCompatibility

group = 'example.org'
version = '0.0.1-SNAPSHOT'

dependencies {
    compile group: 'org.owasp', name: 'dependency-check-gradle', version: '6.0.1'
    compile group: 'org.padler.gradle.minify', name: 'gradle-minify-plugin', version: '1.5.1'
}

dependencyCheck {
    format= 'ALL'
    skipConfigurations = ['compileOnly','compileClasspath']
    cve {
        urlModified = 'https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-modified.json.gz'
        urlBase = 'https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-%d.json.gz'
    }
}
```

Then I ran:
```
$ ./gradlew dependencyCheckUpdate

BUILD SUCCESSFUL in 22s
1 actionable task: 1 executed
```

What version of gradle are you using?

**Comment by markjfisher** [comment]
I tried gradle 6.3 and 6.6.1. The gradle script I provided is stand alone, and does not compile with 5.2.3 or onwards, but works fine with 5.2.2.

**Comment by markjfisher** [comment]
$ gradle -version
    
    ------------------------------------------------------------
    Gradle 6.6.1
    ------------------------------------------------------------
    
    Build time:   2020-08-25 16:29:12 UTC
    Revision:     f2d1fb54a951d8b11d25748e4711bec8d128d7e3
    
    Kotlin:       1.3.72
    Groovy:       2.5.12
    Ant:          Apache Ant(TM) version 1.10.8 compiled on May 10 2020
    JVM:          11.0.7 (Azul Systems, Inc. 11.0.7+10-LTS)
    OS:           Linux 5.4.0-47-lowlatency amd64
    
    $ gradle
    Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details
    
    > Task :help
    
    Welcome to Gradle 6.6.1.
    
    To run a build, run gradle <task> ...
    
    To see a list of available tasks, run gradle tasks
    
    To see a list of command-line options, run gradle --help
    
    To see more detail about a task, run gradle help --task <task>
    
    For troubleshooting, visit https://help.gradle.org
    
    BUILD SUCCESSFUL in 3s
    1 actionable task: 1 executed


Change the version in the script to 5.2.3:

    $ gradle
    
    > Configure project :
    e: /home/markf/dev/work/jl/owasp-test/build.gradle.kts:11:7: Type mismatch: inferred type is () -> Unit but Closure<(raw) Any!>! was expected
    e: /home/markf/dev/work/jl/owasp-test/build.gradle.kts:12:5: Unresolved reference: urlModified
    e: /home/markf/dev/work/jl/owasp-test/build.gradle.kts:13:5: Unresolved reference: urlBase
    
    FAILURE: Build failed with an exception.
    
    * Where:
    Build file '/home/markf/dev/work/jl/owasp-test/build.gradle.kts' line: 11
    
    * What went wrong:
    Script compilation errors:
    
      Line 11:   cve {
                     ^ Type mismatch: inferred type is () -> Unit but Closure<(raw) Any!>! was expected
    
      Line 12:     urlModified = "https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-modified.json.gz"
                   ^ Unresolved reference: urlModified
    
      Line 13:     urlBase = "https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2020.json.gz"
                   ^ Unresolved reference: urlBase
    
    3 errors
    
    * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
    
    * Get more help at https://help.gradle.org
    
    BUILD FAILED in 3s

**Comment by markjfisher** [comment]
Ok, I think this is a kotlin gradle script issue, as I've just changed the build script to groovy format, and it's working.

This works (build.gradle):

    plugins {
        id 'org.owasp.dependencycheck' version '5.2.3'
    }
    
    repositories {
        mavenCentral()
    }
    
    dependencyCheck {
      cve {
        urlModified = "https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-modified.json.gz"
        urlBase = "https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2020.json.gz"
      }
    }

This does not work, although it's technically identical (build.gradle.kts):

    plugins {
      id("org.owasp.dependencycheck") version "5.2.3"
    }
    
    repositories {
      mavenCentral()
    }
    
    dependencyCheck {
      cve {
        urlModified = "https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-modified.json.gz"
        urlBase = "https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2020.json.gz"
      }
    }

**Comment by jeremylong** [comment]
Also - just to point out that your URl base has 2020 - that should be replaced with %d. Otherwise you are only including data from the 2020 NVD data feed.

```groovy
  cve {
    urlModified = "https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-modified.json.gz"
    urlBase = "https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-%d.json.gz"
  }
```

**Comment by markjfisher** [comment]
yes, sorry, i copied this from a colleague's version, my own in our actual project has %d in it (I even pointed this out to them!)

**Comment by ChriFo** [comment]
@markjfisher The Kotlin compatible config have to looks like this:
```
dependencyCheck {
    cve.urlModified = "https://artifacts.ehex.de/repository/nist-data-mirror/nvdcve-1.1-modified.json.gz"
    cve.urlBase = "https://artifacts.ehex.de/repository/nist-data-mirror/nvdcve-1.1-%d.json.gz"
}
```

**Comment by markjfisher** [comment]
excellent news @ChriFo ! I'll try this out tomorrow.
