### ISSUE TITLE
How to use this with Android projects?

### ISSUE THREAD

**Issue by mirabilos** [dependency-check/dependency-check-gradle#206]
I’ve got the following already under `allprojects`:

    apply plugin: 'org.owasp.dependencycheck'
    dependencyCheck {
        failBuildOnCVSS = 8
        scanSet = [project.layout.projectDirectory.dir("src").asFile]
        skipConfigurations += 'lintClassPath'
    }
    // doesn’t work: tasks.findByName("check")?.dependsOn(dependencyCheckAnalyze)

But I can’t get it to run on a simple `./gradlew clean build` in the top-level of the project, let alone on a `../gradlew clean build` in a subproject (this one has a library and an äpp as modules, and I need to check them both independently, if run so, and as a whole, if building the whole thing).

The `scanSet` is from [our normal OWASP check plugin configuration for Maven projects](https://github.com/tarent/rfc822/blob/2143dc8f4af8422ab139ef17cd03b638333d5512/pom.xml#L119..L130) (I don’t know Gradle at all, but I’ve built up almost a decade of Maven experience by now, but Android forces me to use Gradle ☹), and the `skipConfigurations` is to avoid triggering `score > 8` build failures for something in IntelliJ (?) [on even an empty project](https://stackoverflow.com/a/61247749/2171120).

Furthermore, I don’t see the differece between `dependencyCheckAnalyze`[sic!] and `dependencyCheckAggregate` explained in an understandable way: from [the Tasks documentation](https://jeremylong.github.io/DependencyCheck/dependency-check-gradle/configuration-aggregate.html) I think I need Aggregate in a multi-module project (so, *every* Android project, because they are always structured as top-level plus `app/` subdirectory), but https://github.com/jeremylong/dependency-check-gradle#what-if-my-project-includes-multiple-sub-project-how-can-i-use-this-plugin-for-each-of-them-including-the-root-project says nothing about it and somewhere else I think I saw Analyse used, not Aggregate… 😕

**Comment by noloman** [comment]
any update on this?

**Comment by jeremylong** [comment]
Anyone have an example project that fails? From the above question - I have no clue what is going on. If we have a concrete example I can help.

**Comment by noloman** [comment]
> Anyone have an example project that fails? From the above question - I have no clue what is going on. If we have a concrete example I can help.

I just posted [a new issue](https://github.com/dependency-check/dependency-check-gradle/issues/372) which is related to a failing Android project

**Comment by noloman** [comment]
> I’ve got the following already under `allprojects`:
> 
> ```
> apply plugin: 'org.owasp.dependencycheck'
> dependencyCheck {
>     failBuildOnCVSS = 8
>     scanSet = [project.layout.projectDirectory.dir("src").asFile]
>     skipConfigurations += 'lintClassPath'
> }
> // doesn’t work: tasks.findByName("check")?.dependsOn(dependencyCheckAnalyze)
> ```
> 
> But I can’t get it to run on a simple `./gradlew clean build` in the top-level of the project, let alone on a `../gradlew clean build` in a subproject (this one has a library and an äpp as modules, and I need to check them both independently, if run so, and as a whole, if building the whole thing).
> 
> The `scanSet` is from [our normal OWASP check plugin configuration for Maven projects](https://github.com/tarent/rfc822/blob/2143dc8f4af8422ab139ef17cd03b638333d5512/pom.xml#L119..L130) (I don’t know Gradle at all, but I’ve built up almost a decade of Maven experience by now, but Android forces me to use Gradle ☹), and the `skipConfigurations` is to avoid triggering `score > 8` build failures for something in IntelliJ (?) [on even an empty project](https://stackoverflow.com/a/61247749/2171120).
> 
> Furthermore, I don’t see the differece between `dependencyCheckAnalyze`[sic!] and `dependencyCheckAggregate` explained in an understandable way: from [the Tasks documentation](https://jeremylong.github.io/DependencyCheck/dependency-check-gradle/configuration-aggregate.html) I think I need Aggregate in a multi-module project (so, _every_ Android project, because they are always structured as top-level plus `app/` subdirectory), but [jeremylong/dependency-check-gradle#what-if-my-project-includes-multiple-sub-project-how-can-i-use-this-plugin-for-each-of-them-including-the-root-project](https://github.com/jeremylong/dependency-check-gradle#what-if-my-project-includes-multiple-sub-project-how-can-i-use-this-plugin-for-each-of-them-including-the-root-project) says nothing about it and somewhere else I think I saw Analyse used, not Aggregate… 😕

I'm might be a bit too late, but you've got instructions [here](https://www.droidcon.com/2021/12/16/keep-your-app-secure-with-dependencycheck/).

A working example:

In the root-level `build.gradle`:

```
If you're using the Gradle Version Catalog:
plugins {
	...
    alias(libs.plugins.dependencyCheck)
	...
}

Otherwise:
plugins {
	...
    id("org.owasp.dependencycheck") version "9.0.8"
	...
}

Just check https://plugins.gradle.org/plugin/org.owasp.dependencycheck
...
allprojects {
    apply plugin: 'org.owasp.dependencycheck'
    dependencyCheck {
        outputDirectory = './build/reports'
        scanConfigurations = configurations.findAll {
            !it.name.startsWithAny('androidTest', 'test', 'debug') &&
                    it.name.contains("DependenciesMetadata") && (
                    it.name.startsWithAny("api", "implementation", "runtimeOnly") ||
                            it.name.contains("Api") ||
                            it.name.contains("Implementation") ||
                            it.name.contains("RuntimeOnly")
            )
        }.collect {
            it.name
        }
        failBuildOnCVSS = 8
        nvd {
            apiKey = API_KEY
        }
    }
```

**Comment by awesome-manuel** [comment]
The following snippet works for Kotlin syntax:
```kotlin
plugins {
	...
    alias(libs.plugins.dependencyCheck)
	...
}
...
allprojects {
    apply { plugin("org.owasp.dependencycheck") }
    dependencyCheck {
        scanConfigurations = configurations.filter {
            listOf("androidTest", "test", "debug").any { !name.startsWith(it) } and
            name.contains("DependenciesMetadata") and
            listOf("Api", "Implementation", "RuntimeOnly").any { name.contains(it) }
        }.map { name }
    }
}
```
