### ISSUE TITLE
Please update jakarta.activation dependency

### ISSUE THREAD

**Issue by paplorinc** [dependency-check/dependency-check-gradle#215]
As shown by Gradle Enterprise (from 2018):
![image](https://user-images.githubusercontent.com/1841944/111625097-c578ec00-87ec-11eb-9357-ef67fc88cb9f.png)

Latest is: https://mvnrepository.com/artifact/com.sun.activation/jakarta.activation/2.0.0

**Comment by jeremylong** [comment]
Please see https://github.com/jeremylong/DependencyCheck/pull/2920

**Comment by jeremylong** [comment]
I reviewed the usage of the mail api and released we could just remove the mail api and the transitive dependency jakarta.activation. When 6.1.4 is released (which should be soon) we no longer have jakarata.activation as a dependency.
