### ISSUE TITLE
How do I scan dependencies present in the buildSrc directory?

### ISSUE THREAD

**Issue by 123tarunanand** [dependency-check/dependency-check-gradle#227]
Since buildSrc is not considered a project, the dependencies present in its build.gradle.kts file are not analyzed. I tried adding it by using these ScanSets -

`scanSet = mutableListOf<File>(File("buildSrc"))`

`scanSet = mutableListOf<File>(File("buildSrc/build.gradle.kts"))`

but it still does not scan buildSrc

**Comment by jeremylong** [comment]
Sorry about the delayed response. The only way to have a second gradle project scanned is to ensure the second gradle project is in the `settings.gradle`. If you want the reports combined into a single report use dependencyCheckAggregate instead of dependencyCheckAnalyze.
