### ISSUE TITLE
False positive on servo-core-0.10.1.jar

### ISSUE THREAD

**Issue by RunFox** [dependency-check/dependency-check-gradle#235]
Hello. I use dependency-check plugin for gradle. 
Version of plugin:6.4.4.1
Version of gradle: 6.8

I see many false positive on servo-core-0.10.1.jar. DC determines three identifiers for this component:

pkg.maven/com.netflix.servo/servo-core@0.10.1
cpe:2.3:a:docker:docker:0.10.1:*
cpe:2.3:a:travis-ci:travis_ci:0.10.1:*

And shows list of cve for docker and travis-ci. It seems like it match only version in cpe

**Comment by RunFox** [comment]
Similar case with servo-internal-0.10.1

**Comment by jeremylong** [comment]
Please report false positives on the main dependency-check repository: https://github.com/jeremylong/DependencyCheck/issues/new?assignees=&labels=FP+Report&template=false-positive-report.yml&title=%5BFP%5D%3A+
