### ISSUE TITLE
Scope of dependency dependency-check-core has changed after 6.4.1

### ISSUE THREAD

**Issue by zarebski-m** [dependency-check/dependency-check-gradle#238]
Up to version 6.4.1, the dependency of `org.owasp:dependency-check-core` was a compile dependency, but in more recent versions (6.4.1.1, 6.5.0.1) it has changed to a runtime-only dependency.

I am configuring build using Gradle buildSrc. For versions up to 6.4.1 the following configuration was working:

```
// buildSrc/build.gradle.kts
dependencies {
    implementation("org.owasp:dependency-check-gradle:6.4.1")
    // ...
}

// buildSrc/src/main/kotlin/project-conventions.gradle.kts
import org.owasp.dependencycheck.reporting.ReportGenerator

dependencyCheck {
    // ...
    formats = listOf(ReportGenerator.Format.JUNIT, ReportGenerator.Format.HTML)
}
```

Starting from version 6.4.1.1 it does not work anymore because `org.owasp.dependencycheck.reporting.ReportGenerator` is not visible. My workaround was to explicitly add `implementation("org.owasp:dependency-check-core:6.5.0")` in `build.gradle.kts` but it would be nice to have just a single plugin dependency with a single version specified.

**Comment by jeremylong** [comment]
Sorry about the delay - we switched from using the `compile` scope for the dependencies to the `implementation` scope. Apparently, we may need to change this to `api`...
