### ISSUE TITLE
Skipping testImplementation configuration does not work

### ISSUE THREAD

**Issue by BenjaDiaz** [dependency-check/dependency-check-gradle#241]
Adding the following configuration should make the plugin ignore dependencies declared as testImplementation, but it does not work.

```

configure<org.owasp.dependencycheck.gradle.extension.DependencyCheckExtension> {
    format = org.owasp.dependencycheck.reporting.ReportGenerator.Format.ALL
    suppressionFile = "suppressions.xml"
    skipConfigurations = mutableListOf("testImplementation")
}
```

Dependencies declared as testImplementation still appear in the findings report.

**Comment by jeremylong** [comment]
should be solved with https://github.com/dependency-check/dependency-check-gradle/pull/242

These should now be excluded by default.  Note that the report does list the configurations the dependency was identified in - any chance the dependency is also in a different scope that is not being skipped?

**Comment by BenjaDiaz** [comment]
It works now. Thank you very much!
