### ISSUE TITLE
setting custom outputDirectory does not output reports

### ISSUE THREAD

**Issue by stealthrabbi** [dependency-check/dependency-check-gradle#243]
with this configuration, reports are printed to build/reports, per documentation, when running `./gradlew dependencyCheckAnalyze`

```
dependencyCheck {
    failBuildOnCVSS=1
    skipTestGroups=false
    format='ALL'
    cveValidForHours=1
}
```

but with specifying the output directory, the files aren't created. Maybe because the directory doesn't get created, but there's no error.

```
dependencyCheck {
    failBuildOnCVSS=1
    skipTestGroups=false
    format='ALL'
    cveValidForHours=1
    outputDirectory='build/reports/dependencyCheck'
}

```

**Comment by firmianay** [comment]
Same problem, did you solve it?

**Comment by MartinHaeusler** [comment]
I've encountered the same issue. Moreover, the plugin will proactively **delete** the given `outputDirectory`. Which is kinda funny :)

**Comment by stealthrabbi** [comment]
@firmianay I have not solved it. I just learned to deal with it being in the default dir.

**Comment by jeremylong** [comment]
@MartinHaeusler ODC does not delete the outputDirectory - the only directory the task deletes is a temporary directory used during the analysis.

@stealthrabbi using your configuration and running odc I get the following which is likely what you don't want and why you can't find the reports:

```shell
$ ./gradlew dependencyCheckAggregate --info
...
Generating report for project gradleProj
Writing report to: /Users/jeremy/.gradle/daemon/6.1.1/build/reports/dependencyCheck/dependency-check-report.xml
Writing report to: /Users/jeremy/.gradle/daemon/6.1.1/build/reports/dependencyCheck/dependency-check-report.html
Writing report to: /Users/jeremy/.gradle/daemon/6.1.1/build/reports/dependencyCheck/dependency-check-report.json
Writing report to: /Users/jeremy/.gradle/daemon/6.1.1/build/reports/dependencyCheck/dependency-check-report.csv
Writing report to: /Users/jeremy/.gradle/daemon/6.1.1/build/reports/dependencyCheck/dependency-check-report.sarif
Writing report to: /Users/jeremy/.gradle/daemon/6.1.1/build/reports/dependencyCheck/dependency-check-junit.xml
...
```

However, if we update the configuration to correctly reference the build directory you will likely get the results you are looking for:

```groovy
dependencyCheck {
    failBuildOnCVSS=1
    skipTestGroups=false
    format='ALL'
    cveValidForHours=1
    outputDirectory="$buildDir/reports/dependencyCheck"
}
```

We can then run ODC and get the reports output in the correct build directory.

```shell
$ ./gradlew dependencyCheckAggregate --info
...
Generating report for project gradleProj
Writing report to: /Users/jeremy/Projects/samples/gradleProj/build/reports/dependencyCheck/dependency-check-report.xml
Writing report to: /Users/jeremy/Projects/samples/gradleProj/build/reports/dependencyCheck/dependency-check-report.html
Writing report to: /Users/jeremy/Projects/samples/gradleProj/build/reports/dependencyCheck/dependency-check-report.json
Writing report to: /Users/jeremy/Projects/samples/gradleProj/build/reports/dependencyCheck/dependency-check-report.csv
Writing report to: /Users/jeremy/Projects/samples/gradleProj/build/reports/dependencyCheck/dependency-check-report.sarif
Writing report to: /Users/jeremy/Projects/samples/gradleProj/build/reports/dependencyCheck/dependency-check-junit.xml
```

**Comment by jeremylong** [comment]
Relative paths work too - but you need to actual specify relative to what? By default it is using `~/.gradle/daemon/6.1.1/`.

So one could use something like:
`outputDirectory="$buildDir/../../../reports/dependencyCheck"`

Or specify an absolute path. If you are having trouble use `--info` and it will show you where the reports are being written.

**Comment by stealthrabbi** [comment]
I assumed the outputDirectory was a relative path from `$buildDir`, given the example in [the readme](https://github.com/dependency-check/dependency-check-gradle#how-to-customize-the-report-directory)

`outputDirectory = "security-report"`

I think having to specify an abs path or path off of the  `$buildDir` root is fine, but I suggest:

1. Updating the readme to give a better example.
2. Produce a warning / error if the build report fails to write out there for any File I/O issue.

**Comment by jeremylong** [comment]
I just updated the readme. If an error writing the report occurs we would produce an error/stacktrace. In this case - the report was just being written to an unexpected directory.
