### ISSUE TITLE
Deprecated configuration warning when running dependencyCheckUpdate and dependencyCheckAggregate together

### ISSUE THREAD

**Issue by adski31** [dependency-check/dependency-check-gradle#246]
Using Gradle 7.4 and plugin version 6.5.3 on a multi-module build. Proxy is configured correctly in ~/.gradle/gradle.properties

Anytime I run both `dependencyCheckUpdate` and `dependencyCheckAggregate` together in the same Gradle command I get the `"Deprecated configuration `proxy { server='my-proxy.example.com' }`; please update your configuration to use the gradle proxy configuration"` warning. No such warning if I run the commands separately.

```
% ./gradlew dependencyCheckUpdate dependencyCheckAggregate
```
[see warning]

```
% ./gradlew dependencyCheckUpdate
% ./gradlew dependencyCheckAggregate
```
[no warnings]

**Comment by adski31** [comment]
Seeing same issue if I replace `dependencyCheckAggregate` with `dependencyCheckAnalyze`.

**Comment by jeremylong** [comment]
Any chance you can share you dependency check configuration in your `build.gradle`?

**Comment by adski31** [comment]
```
dependencyCheck {
  failBuildOnCVSS = 7
  cveValidForHours = 1
  format = 'ALL'
}
```

**Comment by adski31** [comment]
FWIW, configuration does seem to matter. I will add, however, that I do have `systemProp.http.proxyHost`, `systemProp.http.proxyPort` and `systemProp.http.nonProxyHosts` defined in my `~/.gradle/gradle.properties` file.

**Comment by jeremylong** [comment]
I just pieced together what is happening. The warning can obviously be ignored.
