### ISSUE TITLE
Could not find method sha256Checksum() for arguments

### ISSUE THREAD

**Issue by itsnagaraj** [dependency-check/dependency-check-gradle#261]
I tried upgrading to 7.0.0 and got an error when local artefact was included in the scanning. This was not an issue before

```
 Could not find method sha256Checksum() for arguments [com.xyz:common.utils:1.0] on task ':dependencyCheckAggregate' of type org.owasp.dependencycheck.gradle.tasks.Aggregate.
```

Do we need to add new exclusion file whitelisting all internal artefacts? Are there any other workarounds?

**Comment by chadlwilson** [comment]
Dupe of #247, please close.
