### ISSUE TITLE
Change of data.directory due to database purge with 7.0.0

### ISSUE THREAD

**Issue by LarsKaulen** [dependency-check/dependency-check-gradle#264]
Hello, with version 7.0.0 you implemented breaking changes within the data format.
You communicated about this change and the possible need to purge the database within the [release notes](https://github.com/jeremylong/DependencyCheck#700-upgrade-notice).

For my use case, it isn't quite as simple sadly. I use CI (Jenkins) jobs on old (but still supported) releases to monitor those for CVEs with your gradle plugin and potentially upgrade third party libraries and publish a patch release if necessary.
But on those old branches/releases, I obviously want to make as little changes as necessary, to assure minimal impact on users, and therefore don't want to update the dependency check plugin on those branches.

This leads to my problem:
The Jenkins jobs running the CVE checks on older releases all share the gradle home folder.
This means, that I would constantly have to purge the database, so that all branches (those with the 7.x.x and those with the 6.x.x dependency check plugin) still work.

There is a pretty easy solution, as the default `data.directory` value is `${gradleUserHomeDir}/dependency-check-data/5.0` (https://github.com/dependency-check/dependency-check-gradle/blob/main/src/main/groovy/org/owasp/dependencycheck/gradle/extension/DataExtension.groovy#L29) and I could just reconfigure that to e.g. `${gradleUserHomeDir}/dependency-check-data/7.0`.

Now to my question: shouldn't that be the new default anyways?
It seems like you already introduced some sort of versioning structure (with the `5.0` folder), why not change the default to a new one, so that different versions of the plugin could be used "side by side" by one user.

**Comment by LarsKaulen** [comment]
Especially when looking at this commit for the 6.0.0.1 release: https://github.com/dependency-check/dependency-check-gradle/commit/da7eac8738d2cf4edea20b9b600f49b70598321f

**Comment by jeremylong** [comment]
When we released 7.0.0 - I completely forgot to update the `DataExtension.groovy` in the gradle plugin.  Release will be pushed shortly.

**Comment by jeremylong** [comment]
7.0.4.1 has bee released to resolve this issue.  Sorry about this.

**Comment by LarsKaulen** [comment]
No problem, thank you for the patch and your work in general.
