### ISSUE TITLE
 Creating database structure does not work

### ISSUE THREAD

**Issue by robingood** [dependency-check/dependency-check-gradle#267]
Hello,

I am currently trying to execute ./gradlew dependencyCheckUpdate on a project on my local machine and receive a strange error which doesnt allow the Database Structure to be created. Interestingly, another java project using the same gradle version is working so I guess it is a dependency or something in my particular project which causes it to fail. However I dont know that the source is.

./gradlew -v                           

------------------------------------------------------------
Gradle 6.6.1
------------------------------------------------------------

Build time:   2020-08-25 16:29:12 UTC
Revision:     f2d1fb54a951d8b11d25748e4711bec8d128d7e3

Kotlin:       1.3.72
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.8 compiled on May 10 2020
JVM:          11.0.14.1 (Amazon.com Inc. 11.0.14.1+10-LTS)
OS:           Windows 10 10.0 amd64

Error Stack: attached as file (since it is quite long).

Thank you for any hint.
[error_log.txt](https://github.com/dependency-check/dependency-check-gradle/files/8620393/error_log.txt)

**Comment by jeremylong** [comment]
After reviewing some other tickets - running `./gradlew dependencyCheckPurge` resolved the issue.
