### ISSUE TITLE
expose --ossIndexRemoteErrorWarnOnly to gradle plugin

### ISSUE THREAD

**Issue by valicraciun** [dependency-check/dependency-check-gradle#269]
In seems for multiple scans of different projects, we get from time to time Rate limit exceeded error.

It would be great if _--ossIndexRemoteErrorWarnOnly_ can be added tothe gradle plugin in order to only warn instead of failure in case this exception is thrown by OSS Index remote repository

**Comment by jeremylong** [comment]
In some cases, if the OSS index is being used, it is the only source for a vulnerability. There is already a configuration option for `failOnError`: https://jeremylong.github.io/DependencyCheck/dependency-check-gradle/configuration.html
