### ISSUE TITLE
DC ignore nonProxyHosts

### ISSUE THREAD

**Issue by RunFox** [dependency-check/dependency-check-gradle#276]
Version of dependency-check-gradle: 7.1.2
Hello! I try to configure dc-gradle in build.gradle file and specify some host with no proxy like:
`
dependencyCheck{
   proxy {
      nonProxyHosts=['my-host.com']
   }
}
`
But next I see that DC ignore that options and try to connect to my-host.com through a proxy.
What I should to do to work with this option?

**Comment by aikebah** [comment]
Try changing the list of String to a single string of comma-separated exclusions (just like the system property nonProxyHosts). Gut feel (not a gradle user) is that it will work, as the target property of Settings that the nonProxyHosts config goes into is expecting a comma-separated-hosts-string.

**Comment by jeremylong** [comment]
This will be resolved with https://github.com/dependency-check/dependency-check-gradle/pull/286.
