### ISSUE TITLE
error when yarn is not installed

### ISSUE THREAD

**Issue by demSly** [dependency-check/dependency-check-gradle#279]
Hi, I am running a Gitlab pipeline (log here https://gitlab.com/velox-shop/commons/-/jobs/3124338908)

It is a Java project, so yarn is not installed.

I'm using plugin `id "org.owasp.dependencycheck" version "7.2.1"`  and I get a 
`InitializationException: Unable to read yarn audit output.
[1274](https://gitlab.com/velox-shop/commons/-/jobs/3124338908#L1274)		caused by IOException: Cannot run program "yarn": error=2, No such file or directory
[1275](https://gitlab.com/velox-shop/commons/-/jobs/3124338908#L1275)		caused by IOException: error=2, No such file or directory`

**Comment by demSly** [comment]
I solved this by adding
```
dependencyCheck {
    analyzers {
        nodeAudit {
            yarnEnabled=false
        }
    }
}
```
but I still think it should work without.

**Comment by jeremylong** [comment]
I just ran ODC on `https://gitlab.com/velox-shop/commons` and did not receive the error message. The error indicates a `yarn.lock` file was scanned - and because `yarn` is not installed the analysis cannot be completed.
