### ISSUE TITLE
Tag  7.4.0 points to the wrong commit

### ISSUE THREAD

**Issue by TWiStErRob** [dependency-check/dependency-check-gradle#296]
https://github.com/dependency-check/dependency-check-gradle/compare/v7.3.2..v7.4.0 shows no changes
Tag shows no commits since 7.3.2: https://github.com/dependency-check/dependency-check-gradle/commits/v7.4.0
[Tag](https://github.com/dependency-check/dependency-check-gradle/tree/v7.4.0) is "This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository."

please force push v7.4.0 as this commit: https://github.com/dependency-check/dependency-check-gradle/commit/93114b9e98c8f29763ae4d74b46d88e6ef574afe

**Comment by jeremylong** [comment]
No - the 7.4.0 tag points to the actual release code. As documented in #295 there was a mistake during the release. 7.4.1 will be released shortly.

**Comment by TWiStErRob** [comment]
Note: if there were no changes in 7.4.0 then it's equivalent to 7.3.2, so by semver you should increment 7.5.0. but I guess then you'll get out of sync with the core library.
