### ISSUE TITLE
Casting error in 7.4.1 when processing nonProxyHosts configuration

### ISSUE THREAD

**Issue by cula011** [dependency-check/dependency-check-gradle#297]
Still having an issue with proxy settings, now in 7.4.1. It looks to be getting further since https://github.com/dependency-check/dependency-check-gradle/issues/291 was resolved, but now it is failing with the following:
 
```
Execution failed for task ':service:dependencyCheckAnalyze'.
> Cannot cast object 'localhost|127.0.0.1' with class 'java.lang.String' to class 'java.util.List'`

Caused by: org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object 'localhost|127.0.0.1|192.168.1.1' with class 'java.lang.String' to class 'java.util.List'
        at org.owasp.dependencycheck.gradle.extension.ProxyExtension.setProperty(ProxyExtension.groovy)
        at org.owasp.dependencycheck.gradle.tasks.ConfiguredTask.configureProxy(ConfiguredTask.groovy:204)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

It seems it is trying to assign a String to a List\<String\>:
https://github.com/dependency-check/dependency-check-gradle/blob/bfc6edacafa53df6495d5d61049e62a1698ae8ea/src/main/groovy/org/owasp/dependencycheck/gradle/tasks/ConfiguredTask.groovy#L204

See target:
https://github.com/dependency-check/dependency-check-gradle/blob/bfc6edacafa53df6495d5d61049e62a1698ae8ea/src/main/groovy/org/owasp/dependencycheck/gradle/extension/ProxyExtension.groovy#L30

Looking at the history, it was previously fetching the `nonProxyHosts` differently, which was returning a List\<Pattern\>:
https://github.com/dependency-check/dependency-check-gradle/blob/2475268547fc8c081a9516b17f0c256fa168817b/src/main/groovy/org/owasp/dependencycheck/gradle/tasks/ConfiguredTask.groovy#L207

Now, It is simply fetching a single String:
https://github.com/dependency-check/dependency-check-gradle/blob/bfc6edacafa53df6495d5d61049e62a1698ae8ea/src/main/groovy/org/owasp/dependencycheck/gradle/tasks/ConfiguredTask.groovy#L188

**Comment by jeremylong** [comment]
all the reasons I hate groovy...  I really need to add `@groovy.transform.CompileStatic`...

**Comment by jeremylong** [comment]
Added `@CompileStatic` and was surprised by the number of issues. See https://github.com/dependency-check/dependency-check-gradle/pull/299

**Comment by cula011** [comment]
Hi @jeremylong, do you have an ETA for the 7.4.2 release? Thanks.
