### ISSUE TITLE
Add option to use older version in dependencyCheck block 

### ISSUE THREAD

**Issue by Grimoren** [dependency-check/dependency-check-gradle#310]
This is the second time a major version bump ( version 8) has disrupted all of our reports, the last being the first version 7 upgrade. 

Since dependency-check-gradle is a plugin, the version has to be specified in the build script or in the first block after the build script.
This fact makes it impossible to change it without making a change to all the repositories individually. 

If we added the option to use an older version in the dependencyCheck { } block we could specify the option in our shared version control build.gradle file which would make it possible for use to keep using the "latest.release" instead of having to pin every time something goes wrong in the latest version. 

jacoco does something similar in their plugin:

jacoco {
    toolVersion = "0.8.8"
}

**Comment by jeremylong** [comment]
This is not possible with how dependency-check works.
