### ISSUE TITLE
Dependency check fails on lower-case formats

### ISSUE THREAD

**Issue by arjopoldervaart** [dependency-check/dependency-check-gradle#312]
We get: 
```
Execution failed for task ':common-workflow-actions-ear:dependencyCheckAnalyze'.
> No enum constant org.owasp.dependencycheck.reporting.ReportGenerator.Format.csv
```
when we run our Gradle builds with version 8.0.1.

Our config is:
```
dependencyCheck {
    failBuildOnCVSS=0
    formats=['csv', 'html']
    suppressionFiles = ["${rootDir}/config/owasp/suppression.xml"]
}
```
When  we change this to upper case or revert to version 7.4.4 the build runs. 
I read in the documentation that the formats now have to match the enums exactly, but is it possible to ignore case? This impacts all our 100+ builds.

Kind regards, Arjo

**Comment by arjopoldervaart** [comment]
Hi,

Can you please provide an update? Can this be fixed or do we need to update all our repositories?

**Comment by jeremylong** [comment]
This happened when I added `@groovy.transform.CompileStatic` to most classes/methods in the plugin. I'll submit a PR fixing this shortly.

**Comment by jeremylong** [comment]
Fix will be included in the next release.

**Comment by arjopoldervaart** [comment]
Hi Jeremy,

Thanks a lot! This saves us a lot of work!

Kind regards, Arjo
