### ISSUE TITLE
Release 8.1.0

### ISSUE THREAD

**Issue by TWiStErRob** [dependency-check/dependency-check-gradle#326]
Hi, we got a release 8.1.0 PR https://github.com/detekt/sarif4k/pull/37, but in this repo there's no commit/tag/release/changelog/readme associated with it.

**Comment by jeremylong** [comment]
sorry - forgot to push the tag to the gradle plugin. its there now.

**Comment by TWiStErRob** [comment]
Did you also forget to push `main`?

https://github.com/dependency-check/dependency-check-gradle/tree/v8.1.0

![image](https://user-images.githubusercontent.com/2906988/221298388-6b859687-9c28-4040-947d-2460b77ebdcb.png)

**Comment by jeremylong** [comment]
Sorry about that. Fixed.  My normal routine for the release got messed up because the nexus server I publish to central through was having issues and timed out repeatedly...

**Comment by TWiStErRob** [comment]
No worries, only thing I wanted to see was what changed :)
