### ISSUE TITLE
README does not reflect breaking change in format configuration introduced in 8.1.0

### ISSUE THREAD

**Issue by OliverO2** [dependency-check/dependency-check-gradle#331]
#324 introduced a breaking change without documentation. The `format` configuration described in the README's Kotlin DSL example should now include a `.toString()` invocation as in:

```kotlin
dependencyCheck {
    format = org.owasp.dependencycheck.reporting.ReportGenerator.Format.ALL.toString()
}
```

A downside of the approach taken: We lose type safety for the `format` value.

**Comment by jeremylong** [comment]
We accept PRs.

Yes, we lose type safety - but users can create custom templates to output in whatever format they choose.
