### ISSUE TITLE
With Sonallint plugin dependencycheck fails

### ISSUE THREAD

**Issue by rajeshsamalblumeG** [dependency-check/dependency-check-gradle#335]
If I use below plugin together for java application
 classpath 'org.owasp:dependency-check-gradle:8.2.1'
 classpath 'name.remal.gradle-plugins.sonarlint:sonarlint:3.0.8'

apply plugin: 'org.owasp.dependencycheck'
apply plugin: 'name.remal.sonarlint'

> Task :dependencyCheckAnalyze
The Yarn Audit Analyzer has been disabled. Yarn executable was not found.
Exception occurred initializing Yarn Audit Analyzer.

An unexpected error occurred during analysis of 'C:\Users\RAJESH~1.SAM\AppData\Local\Temp\dctemp659d7154-4928-4659-a245-5db3576048d3\check3997599348955
249549tmp\145\package\node_modules\typescript\lib\typescript.js' (RetireJS Analyzer): Java heap space

But if i remove :  apply plugin: 'name.remal.sonarlint'

It works.

> Task :dependencyCheckAnalyze
Verifying dependencies for project core-deploy
Checking for updates and analyzing dependencies for vulnerabilities
Generating report for project core-deploy
Found 92 vulnerabilities in project core-deploy

Tried to disable nodeAnalyser, nodeAudit both. Still same issue.

**Comment by jeremylong** [comment]
The sonarlint plugin is a different project. I do not maintain or support the ODC sonarlint plugin.
