### ISSUE TITLE
Typo in notCompatibleWithConfigurationCache reason

### ISSUE THREAD

**Issue by ianbrandt** [dependency-check/dependency-check-gradle#341]
The [`notCompatibleWithConfigurationCache()`](https://docs.gradle.org/current/javadoc/org/gradle/api/Task.html#notCompatibleWithConfigurationCache-java.lang.String-) reason references the "gradle-versions-plugin", whereas "dependency-check-gradle" is probably what was intended:

https://github.com/dependency-check/dependency-check-gradle/blob/7bf00bdc7be449fa76da3763862a9882f3a42abf/src/main/groovy/org/owasp/dependencycheck/gradle/tasks/AbstractAnalyze.groovy#L738

**Comment by jeremylong** [comment]
Resolved with https://github.com/dependency-check/dependency-check-gradle/pull/345
