### ISSUE TITLE
GitHub releases out of date

### ISSUE THREAD

**Issue by ianbrandt** [dependency-check/dependency-check-gradle#342]
It appears the current latest published version of this plugin is [8.2.1](https://plugins.gradle.org/plugin/org.owasp.dependencycheck/8.2.1), but the latest release tagged in GitHub is [8.1.2](https://github.com/dependency-check/dependency-check-gradle/releases/tag/v8.1.2). The [Current Release](https://github.com/dependency-check/dependency-check-gradle#current-release) badge in the README.md shows 8.2.1, but the [Usage](https://github.com/dependency-check/dependency-check-gradle#usage) section shows 8.1.2. Due to the similarities on the numbers, I initially thought one or the other might be a typo.

It would be nice if the GitHub release tags were kept in sync with the published versions. It would also help those watching this repo for releases.

**Comment by jeremylong** [comment]
Somehow I missed tagging the last release - sorry about that. 8.3.1 is pending a resolution to https://github.com/dependency-check/dependency-check-gradle/issues/339.

**Comment by jeremylong** [comment]
8.3.1 should be released shortly - https://github.com/dependency-check/dependency-check-gradle/pull/345

**Comment by ianbrandt** [comment]
It looks like [8.3.1 has been published](https://plugins.gradle.org/plugin/org.owasp.dependencycheck/8.3.1), and [tagged](https://github.com/dependency-check/dependency-check-gradle/releases/tag/v8.3.1), but the [latest GitHub release](https://github.com/dependency-check/dependency-check-gradle/releases) is still 8.1.2. I think a [release still needs to be created](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository#creating-a-release) for the 8.3.1 tag.
