### ISSUE TITLE
NVD API 2.0 plans?

### ISSUE THREAD

**Issue by LPmaverick** [dependency-check/dependency-check-gradle#349]
https://github.com/stevespringett/nist-data-mirror/ it mentions that the NVD data feeds will be decommissioned later this year.  Based on the logs I have seen using this plugin, I believe it uses these data feeds.  Is that correct?  If so, are there any plans to update to the new NVD API?

Additionally, per http://jeremylong.github.io/DependencyCheck/data/index.html , will mirroring and snapshotting all of the CVE information still be possible

**Comment by jeremylong** [comment]
See https://github.com/jeremylong/DependencyCheck/issues/4732

Mirrors will be made using https://github.com/jeremylong/Open-Vulnerability-Project
