### ISSUE TITLE
Unsupported class file major version 65 when try to upgrade the Owasp latest 9.0.0 version in Android

### ISSUE THREAD

**Issue by manojKumar-L** [dependency-check/dependency-check-gradle#364]
When I try to upgrade to the latest 9.0.0 version, my compiler throws the error as **Unsupported class file major version 65**,
In my project, I'm using the Java version 17 and the Gradle plugin version 8.1.4; does this new version of Owasp not support those versions, or is there anything else I'm missing?

Your assistance will be much appreciated. Thanks

**Comment by jeremylong** [comment]
Fantastic.  I did a little more research on this and have filed [gradle/gradle/issus/27156](https://github.com/gradle/gradle/issues/27156). I will have to look into downgrading H2 in the gradle plugin... But I doubt this will work as smoothly as I hope...

**Comment by jeremylong** [comment]
This should be resolved with 9.0.1 - the dependency upgrade for H2 in 9.0.0 was reverted with the 9.0.1 release.

**Comment by manojKumar-L** [comment]
Thanks for the quick turnaround @jeremylong, It works as expected with the 9.0.1 version

**Comment by bvwidt** [comment]
Is it possible that this issue snuck back in with 9.1.0?

I have been using Gradle 8.0 with the Dependency Check Gradle Plugin 9.1.0.
It works with Gradle 8.0 and the Plugin with the version 9.0.1 oder with Gradle 8.4 and the Plugin with version 9.1.0.

**Comment by langsmith** [comment]
> Is it possible that this issue snuck back in with 9.1.0?

@bvwidt , I'm also seeing the `Unsupported class file major version 65` issue with `9.1.0`

**Comment by pschmidt88** [comment]
Yes, I'm also seeing this with `9.2.0`.

Gradle 7.6.3
Java 17

**Comment by pschmidt88** [comment]
I see. Thank you!
