### ISSUE TITLE
NVD api requests are failing in version 9.0.1

### ISSUE THREAD

**Issue by joost-klitsie** [dependency-check/dependency-check-gradle#367]
I have written a gradle plugin, which was working just fine until I upgraded to 9.0.1 and added an API key to NVD, as I was warned about I should use my own API key.
However, it does not work. I am getting the following:

```
Verifying dependencies for project database
Checking for updates and analyzing dependencies for vulnerabilities

NVD API request failures are occurring; retrying request for the 1 time
```

I think I saw 503 and 403 error status codes as well in my CLI.
I did check my API key with running curl commands, and they return 200's so I am pretty sure it is set up correctly:

curl -I -H "apiKey: xxx-xxx-masked-xxx-xxx" https://services.nvd.nist.gov/rest/json/cves/2.0?resultsPerPage=1&startIndex=0

I am using the following gradle setup:
```
fun Project.configureOwaspDependencyCheck() {
	pluginManager.apply("org.owasp.dependencycheck")
	dependencyCheck {
		failBuildOnCVSS = 0f
		scanConfigurations = configurations.filter {
			!it.name.startsWithAny("androidTest", "test", "debug") &&
					it.name.contains("DependenciesMetadata") && (
					it.name.startsWithAny("api", "implementation", "runtimeOnly") ||
							it.name.contains("Api") ||
							it.name.contains("Implementation") ||
							it.name.contains("RuntimeOnly")
					)
		}.map {
			it.name
		}
		nvd.apiKey = NVDApiKey
		nvd.maxRetryCount = 0
		suppressionFile = "${rootProject.projectDir}/owasp_dependency_check_suppression.xml"
	}
}
```

As mentioned, before updating to version 9 and before using nvd properties, it was doing just fine. Am I missing something here? (also maxRetryCount  can be any value, putting it to 0 just makes not fail 13 times in a row but only 1 :) )

**Comment by jeremylong** [comment]
this is being tracked here: https://github.com/jeremylong/DependencyCheck/issues/6149

**Comment by chadlwilson** [comment]
For what it's worth, I have a workflow that is working pretty reliably within Gradle for the last couple of days now on `9.0.2`, using a Nexus server as mutable for a mutable cache of the entire dependency check data directory (there are easier approaches available for this caching if you use GitHub Actions) which gets downloaded/unzipped/populated prior to each run, and then re-uploaded/cached after each run.

Dependency check is run on every merge, as well as once daily to produce a report.

**Comment by joost-klitsie** [comment]
@jeremylong sadly in version 9.0.2 I am still unsuccessful, if in version 9.0.3 I still don't have success I will open a new issue and try to add more info to it.
