### ISSUE TITLE
False positives with conflicted version resolution

### ISSUE THREAD

**Issue by scottkennedy** [dependency-check/dependency-check-gradle#370]
I'm seeing a reported issue with `gson-2.8.5.jar`,

with:
```
Included by:
pkg:maven/com.plaid/plaid-java@18.0.0
```

But the dependency graph has:
```
+--- com.plaid:plaid-java:18.0.0
|    +--- com.squareup.retrofit2:retrofit:2.9.0
|    |    \--- com.squareup.okhttp3:okhttp:3.14.9 -> 4.11.0 (*)
|    +--- com.squareup.retrofit2:converter-gson:2.9.0
|    |    +--- com.squareup.retrofit2:retrofit:2.9.0 (*)
|    |    \--- com.google.code.gson:gson:2.8.5 -> 2.10.1
```

Due to a newer version of gson being included elsewhere, Gradle is resolving that old transitive dependency to 2.10.1, and including that in the build.

Every gson line in the dependency graph is `com.google.code.gson:gson:2.8.5 -> 2.10.1`.  I can't see any actual instance of 2.8.5 being included in the build.

**Comment by jeremylong** [comment]
Does the report list both versions?

**Comment by scottkennedy** [comment]
The report from `dependency-check-gradle` only lists 2.8.5.  Everything in the Gradle dependency graph shows it's resolved to 2.10.1.

**Comment by scottkennedy** [comment]
Hmm I added a constraint, and it resolved this.  So, never mind.

**Comment by sergeykad** [comment]
This issue still exists. I am unsure what workaround @scottkennedy used, but it would be great if this filtering could be part of the plugin. Otherwise, there are many false positives.

**Comment by vdmitrienko** [comment]
Confirming that the issue is still reproducible 🐛 

We declare a constraint to use version `9.4.57.v20241219` instead of `9.4.53.v20231009` for our transitive dependencies. However, the report still complains about CVEs found in the `9.4.53.v20231009`.
```groovy
dependencies {
    constraints {
        implementation('org.eclipse.jetty:jetty-webapp:9.4.57.v20241219')
    }
}
``` 
`./gradlew dependencies` output:
```
org.eclipse.jetty:jetty-webapp:9.4.53.v20231009 -> 9.4.57.v20241219
```

@jeremylong could you suggest any workaround?

**Comment by vdmitrienko** [comment]
@sergeykad, you might find this issue helpful: https://github.com/dependency-check/dependency-check-gradle/issues/442
