### ISSUE TITLE
Dependency report configuration (size)

### ISSUE THREAD

**Issue by noloman** [dependency-check/dependency-check-gradle#374]
Hi!

In the dependency check report I read:
`Dependencies Scanned: 1470 (1153 unique)`

Because of this I guess, the size of the `dependency-check-report.html` file size is around 108 megabytes.

I really need to reduce the size of this, and I tried the following so for example, only the vulnerable dependencies are shown in the report:

```
dependencyCheck {
        analyzers {
            retirejs {
                filterNonVulnerable = true
            }
        }
}
```

However this isn't working, as it's still showing all the dependencies, and there's no different between using the `filterNonVulnerable` or not.

**Comment by jeremylong** [comment]
Depending on your use case - there are several report formats. HTML is the most verbose and likely the largest, but the XML, JSON, SARIF, and even CSV formats are smaller. Note that the CSV format is not very useful to determine if there are false positives.

**Comment by jeremylong** [comment]
You can even make a copy of the report velocity templates and create your own report.
