### ISSUE TITLE
Redacting the HTML Report

### ISSUE THREAD

**Issue by Zuplyx** [dependency-check/dependency-check-gradle#382]
Hello,

we would like to publish the HTML report with each release of our product. But the report includes some fields which contain internal information which we do not want to expose in a public report. These fields are: `File Path`, `Referenced In Projects/Scopes` and `Included By`.

Is there a way to create a 'redacted' version of the report which does not include these fields?

**Comment by aikebah** [comment]
I think you can create a custom derivative of the default html report template (or even build one fitting just your needs from scratch) and configure the plugin to use that as the report template.

The ([format configuration parameter](http://jeremylong.github.io/DependencyCheck/dependency-check-gradle/configuration.html)) can ([undocumented feature](https://github.com/jeremylong/DependencyCheck/blob/c5209dc87b3c8e81ae8308ae3dda1c0b1284d46e/core/src/main/java/org/owasp/dependencycheck/reporting/ReportGenerator.java#L311...L315)) take fully-qualified or classpath-relative filepath for  a custom template file in addition to the documented strings for the built-in report templates



The packaged template for HTML report can be found at https://github.com/jeremylong/DependencyCheck/blob/main/core/src/main/resources/templates/htmlReport.vsl
