### ISSUE TITLE
Can props from build.gradle.kts be overwritten with -D or -P parameter?

### ISSUE THREAD

**Issue by vring0** [dependency-check/dependency-check-gradle#383]
I want to call parameters via OS command line. I tried different options, but none of them work. For example:
```bash
gradlew dependencyCheckAggregate -Porg.owasp.dependencycheck.data.directory=/owasp
gradlew dependencyCheckAggregate -PdependencyCheck.data.directory=/owasp
gradlew dependencyCheckAggregate -Dorg.owasp.dependencycheck.data.directory=/owasp
gradlew dependencyCheckAggregate -Ddependencycheck.data.directory=/owasp
gradlew dependencyCheckAggregate -DdataDirectory=/owasp
````
Can anyone suggest a working solution?

**Comment by jeremylong** [comment]
You would use the same property names as found in the settings.java - which can also be seen in some of the property files used:

- https://github.com/jeremylong/DependencyCheck/blob/5df22e2a86ecef5822239122958403363f347641/utils/src/main/java/org/owasp/dependencycheck/utils/Settings.java#L143
- https://github.com/jeremylong/DependencyCheck/blob/5df22e2a86ecef5822239122958403363f347641/core/src/main/resources/dependencycheck.properties#L17

**Comment by vring0** [comment]
Thank you! I was able to use the command line to pass these parameters and others. But I had a problem with the parameters that I specified below: -DoutputDirectory and -Dodc.outputDirectory do not give results, scanProjects and formats are lists, it’s not entirely clear how to pass them through the command line.

```kts
dependencyCheck {
    outputDirectory = "$buildDir/dependency-check/report"
    scanProjects = listOf(
        ":app",
        ":app-test",
    )
    formats = listOf("HTML", "JSON")
}
```

**Comment by efasel** [comment]
That didn’t work for me as well. And I don’t think it can. 

The gradle plugin configuration is done via nested extensions:
* https://github.com/dependency-check/dependency-check-gradle/blob/adb51a588d7083490e41e5e12f77e01d2f254612/src/main/groovy/org/owasp/dependencycheck/gradle/DependencyCheckPlugin.groovy#L53
* [DependencyCheckExtension](https://github.com/dependency-check/dependency-check-gradle/blob/main/src/main/groovy/org/owasp/dependencycheck/gradle/extension/DependencyCheckExtension.groovy)
  * [NvdExtension](https://github.com/dependency-check/dependency-check-gradle/blob/main/src/main/groovy/org/owasp/dependencycheck/gradle/extension/NvdExtension.groovy)
  * …

It would be super handy to be able to configure e.g. `nvd.api.delay` on the command line via `-D` or `-P`.
