### ISSUE TITLE
Gradle Version Used in 9.1.0

### ISSUE THREAD

**Issue by rupreck** [dependency-check/dependency-check-gradle#389]
[Edited]

Hello,

We are seeing this issue appear in our analysis using this plugin version 9.1.0

https://github.com/gradle/gradle/issues/24390

This is also discussed here:

https://stackoverflow.com/questions/77225378/gradle-clean-fails-with-gradleexception-failed-to-create-jar-file

After a successful build step in our CI process, we then run gradlew as follows..

gradlew.bat dependencyCheckAggregate --continue  --no-daemon --gradle-user-home C:\Users\XXX\.gradle --info

which gives us this error, which didn't happen in the build step.

01:46:32.8454357 - [1] - FAILURE: Build failed with an exception.
01:46:32.8467216 - [2] - * What went wrong:
01:46:32.8476894 - [3] - A problem occurred configuring root project 'android-member-app-3.git'.
01:46:32.8479329 - [4] - > java.util.concurrent.ExecutionException: org.gradle.api.GradleException: Failed to create Jar file C:\Users\XXX\.gradle\caches\jars-9\7e017447c2dc570ed9c17ba37b0f44ab\jackson-core-2.16.1.jar.
01:46:32.8481646 - [5] - * Try:
01:46:32.8484083 - [6] - > Run with --stacktrace option to get the stack trace.
01:46:32.8486297 - [7] - > Run with --debug option to get more log output.
01:46:32.8488492 - [8] - > Run with --scan to get full insights.
01:46:32.8491046 - [9] - * Get more help at https://help.gradle.org
01:46:32.8492939 - [10] - BUILD FAILED in 8s

Prior to running we update the build.gradle file for the project using the attached script.

[update build.gradle for depcheck.txt](https://github.com/dependency-check/dependency-check-gradle/files/15026980/update.build.gradle.for.depcheck.txt)

Something triggers that noted bug.

Will

**Comment by jeremylong** [comment]
I'm confused - in this case it is the version of gradle you are using, not the version of gradle used to build dependency-check.

**Comment by rupreck** [comment]
Thanks. My mistake... have edited the report.

**Comment by jeremylong** [comment]
What version of gradle are you using?

**Comment by rupreck** [comment]
It is 7.4.2.  

Unusual that it only appears when doing the Dependency Check step in the CI Process. Other steps, including sonar scanner don't trigger it.  The reasons for the gradle bug are in the links I included, but I was hoping there was a workaround for dependency check, or some other change to our setup I could make.

**Comment by jeremylong** [comment]
Try upgrading to 7.6.4 - the [release notes](https://docs.gradle.org/7.6.4/release-notes.html?_gl=1*enpvdv*_ga*MjA1Mzk1NzA5MC4xNzAwNDgwNTMx*_ga_7W7NC6YNPT*MTcxMzcwMDcxMC4xOC4wLjE3MTM3MDA3MTAuNjAuMC4w) state that the bug you are seeing is resolved.

**Comment by rupreck** [comment]
Thanks. We have scheduled an upgrade to solve this. Guess I was hoping there was another way to workaround or avoid it when using Dependency Check.

Thanks for your help.
