### ISSUE TITLE
Please check contains "test" for `skipTestGroups`, not starts with

### ISSUE THREAD

**Issue by Vampire** [dependency-check/dependency-check-gradle#390]
Currently, the `skipTestGroups` only checks for configurations starting with `androidTest` or `test`.
But this does not match things like `integTest...`, `systemTest...`, `functionalTest...`, ...
I think for the default recognition it would be more appropriate to check for `toLowerCase().contains("test")` instead.

To do something like that manually, you need some discouraged work-arounds like in the comments of #22 that reach into the models of all other projects to get all configuration names and then be able to filter on them, or list them all in the root project and hope non get added in subprojects in the future.

**Comment by jeremylong** [comment]
Sorry about the delay, I've had a ton going on outside of my OSS work.  Can you take a look at https://github.com/dependency-check/dependency-check-gradle/pull/392 .

Does that work for you?

**Comment by Vampire** [comment]
Sure, regex check is of course fine too.
I'd probably have done
```groovy
boolean isTestConfiguration = configuration.name =~ /((^|[a-z0-9_])T|(^|_)t)est([A-Z0-9_]|$)/
```
instead though. :-)

**Comment by jeremylong** [comment]
My groovy code looks so much like Java... Fixed: https://github.com/dependency-check/dependency-check-gradle/pull/392/commits/be04e39d1235d1dba34b043cfb251dc8835ae2a6

**Comment by jeremylong** [comment]
slightly more correct:

```groovy
boolean isTestConfiguration = configuration.name ==~ /((^|[a-z0-9_])T|(^|_)t)est([A-Z0-9_]|$)/
```

**Comment by Vampire** [comment]
Well, I wouldn't use Groovy for a public plugin anyway. :-D

**Comment by jeremylong** [comment]
In hindsight I wouldn't either.
