### ISSUE TITLE
Malformed JSON report

### ISSUE THREAD

**Issue by 19mariusz95** [dependency-check/dependency-check-gradle#395]
Hi,

I'm using the OWASP Dependency Check plugin to scan dependencies of my multi-module project running dependencyCheckAggregate task. After running the scan, I download the generated JSON artifacts, but I'm encountering issues with errors in the file structure. Here are some examples of the errors:

- `"url": "ht: "http:`
- `"HIGHEST"}]}]}ST"}]}]}`
- `,"name": "name": "`

**Comment by 19mariusz95** [comment]
I have changed report to XML and I can see that XML is also affected. Examples:

- `</value></evididence type=`
- `</v<value>`

It happens in about 80% of executions, always random different place.

**Comment by jeremylong** [comment]
do you have a sample project that can replicate the issue?

**Comment by 19mariusz95** [comment]
Unfortunately, I cannot share the project because it is a non-public commercial project. The problem only occurs on GitLab CI virtual machines; locally, we haven't encountered this error so far. I wanted to extract the number of vulnerabilities grouped by severity from the reports using a script. For now, I've managed to handle it by parsing with regex instead of parsing XML/JSON.

**Comment by jeremylong** [comment]
without a reproducible error - there isn't much we can do. As you stated, you can't reproduce this locally. No idea what is happening on your CI.
