### ISSUE TITLE
Where is the downloaded data saved?

### ISSUE THREAD

**Issue by landicefu** [dependency-check/dependency-check-gradle#406]
Hi, it takes a really long time for the first time of analyzation to finish, and I think the time is for downloading something from NVD.
I wonder where does those files go after download? If it's possible, I want to persist those across my CI jobs so it can be faster.
Thanks in advance.

**Comment by jeremylong** [comment]
See the documentation here: https://jeremylong.github.io/DependencyCheck/data/index.html

You've got a few options - most people use the [vulnz](https://github.com/jeremylong/Open-Vulnerability-Project/tree/main/vulnz#caching-the-nvd-cve-data) CLI to create a local cache that the host in a location reachable by their CI.
