### ISSUE TITLE
v11.1.0 and 11.0.0 are missing on Maven Central 

### ISSUE THREAD

**Issue by inktomi** [dependency-check/dependency-check-gradle#419]
https://mvnrepository.com/artifact/org.owasp/dependency-check-gradle

Maybe this was an oversight - but it looks like v11 was never pushed to maven central?

**Comment by jeremylong** [comment]
Which docs indicate that 11.0+ is published to central? I need to update
them.

**Comment by inktomi** [comment]
The Readme shows it being pulled in from central.

Nov 6, 2024 3:03:20 PM Jeremy Long ***@***.***>:

**Comment by jeremylong** [comment]
I just created a PR to fix the documentation: https://github.com/dependency-check/dependency-check-gradle/pull/420

See the 11.0.0 upgrade notice: https://github.com/dependency-check/dependency-check-gradle?tab=readme-ov-file#1100-upgrade-notice
