### ISSUE TITLE
Configure URL for maven central

### ISSUE THREAD

**Issue by natan-abolafya** [dependency-check/dependency-check-gradle#427]
Hi. We have started hitting the maven sometimes being down issue, i.e: https://github.com/jeremylong/DependencyCheck/issues/7234

Looks like using central is now the default (though I think the documentation needs an update?) and recommended. I was wondering if there is a way to configure dependencycheck so it uses our nexus proxy for example. I am not even sure if Nexus really supports the tools needed for this but I thought it's worth to ask.

I could see that there is some sort of config https://github.com/jeremylong/DependencyCheck/blob/main/utils/src/main/java/org/owasp/dependencycheck/utils/Settings.java#L666 but I couldn't really figure out setting an arbitrary config.

**Comment by jeremylong** [comment]
Consider looking at the [documentation](https://jeremylong.github.io/DependencyCheck/dependency-check-gradle/configuration.html):

```groovy
analyzers.nexusEnabled = true
analyzers.nexusUrl = 'https://internal.nexus/services/local'
```

**Comment by natan-abolafya** [comment]
:)

That is for Nexus Analyser which we don't have right now. We just have the OSS version. I was just thinking the maven proxy the Nexus has.

Just in case we upgrade to Nexus Pro, does that also override the central URL?

**Comment by jeremylong** [comment]
I don't think nexus proxies the search.
